### ISSUE TITLE
Add validation of JPA Entities against real db schema

### ISSUE THREAD

**Issue by mfvanek** [mfvanek/pg-index-health#113]
Hibernate can do such validation on startup but usually in real apps it isn't an appropriate behavior.

- https://stackoverflow.com/questions/47839163/how-can-i-validate-the-database-schema-against-my-jpa-in-wildfly-11-hibernate
- https://stackoverflow.com/questions/54464978/validate-schema-programmatically-using-hibernate
- https://stackoverflow.com/questions/2327423/how-to-validate-database-schema-programmatically-in-hibernate-with-annotations

**Comment by mfvanek** [comment]
It will not be implemented. It's enough to use Hibernate's validation for such cases.
In application.yml
```yaml
spring:
  jpa:
    hibernate:
      ddl-auto: none
```

In tests (application-test.yml):
```yaml
spring:
  jpa:
    hibernate:
      ddl-auto: validate
```
